# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: booking.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'booking.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbooking.proto\"\x18\n\x06UserID\x12\x0e\n\x06userid\x18\x01 \x01(\t\"\x0e\n\x0c\x42ookingEmpty\"?\n\x0e\x42ookingRequest\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x0f\n\x07movieid\x18\x03 \x01(\t\"8\n\x0b\x42ookingData\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x19\n\x05\x64\x61tes\x18\x02 \x03(\x0b\x32\n.DateEntry\")\n\tDateEntry\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06movies\x18\x02 \x03(\t\"1\n\x0f\x42ookingResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\x9e\x01\n\x07\x42ooking\x12-\n\x12GetBookingByUserID\x12\x07.UserID\x1a\x0c.BookingData\"\x00\x12\x31\n\nAddBooking\x12\x0f.BookingRequest\x1a\x10.BookingResponse\"\x00\x12\x31\n\x0eGetAllBookings\x12\r.BookingEmpty\x1a\x0c.BookingData\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'booking_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERID']._serialized_start=17
  _globals['_USERID']._serialized_end=41
  _globals['_BOOKINGEMPTY']._serialized_start=43
  _globals['_BOOKINGEMPTY']._serialized_end=57
  _globals['_BOOKINGREQUEST']._serialized_start=59
  _globals['_BOOKINGREQUEST']._serialized_end=122
  _globals['_BOOKINGDATA']._serialized_start=124
  _globals['_BOOKINGDATA']._serialized_end=180
  _globals['_DATEENTRY']._serialized_start=182
  _globals['_DATEENTRY']._serialized_end=223
  _globals['_BOOKINGRESPONSE']._serialized_start=225
  _globals['_BOOKINGRESPONSE']._serialized_end=274
  _globals['_BOOKING']._serialized_start=277
  _globals['_BOOKING']._serialized_end=435
# @@protoc_insertion_point(module_scope)
